; INDX_WRITE_STATE - save the INDX state to 0:/sys/indx-state.g
; No motion. INDX_variables.g runs indx-state.g at startup to restore these values.
; Saved: INDX_LC_scale (applied with M558 K0 V), INDX_LC_calibrated, INDX_State, INDX_DEBUG.
; INDX_LC_offset is written as a comment only, because the unloaded reading drifts with
; temperature and calibration must measure it again with INDX_TARE.

if !exists(global.INDX_LC_offset) || !exists(global.INDX_LC_scale) || !exists(global.INDX_LC_calibrated) || !exists(global.INDX_State)
  abort "INDX_WRITE_STATE: INDX globals missing. INDX_variables.g must run from config.g first."

var dbg = exists(global.INDX_DEBUG) ? global.INDX_DEBUG : 0
var f = "0:/sys/indx-state.g"

echo >{var.f} "; INDX persisted state - generated by INDX_WRITE_STATE, do not edit by hand."
echo >>{var.f} "; Run by INDX_variables.g to restore saved values and apply them to the probe."
echo >>{var.f} {"; unloaded baseline when calibrated: " ^ global.INDX_LC_offset ^ " counts"}
echo >>{var.f} {"set global.INDX_LC_scale = " ^ global.INDX_LC_scale}
echo >>{var.f} {"set global.INDX_LC_calibrated = " ^ global.INDX_LC_calibrated}
echo >>{var.f} {"set global.INDX_State = " ^ global.INDX_State}
echo >>{var.f} {"set global.INDX_DEBUG = " ^ var.dbg}
echo >>{var.f} {"M558 K0 V" ^ global.INDX_LC_scale}

if var.dbg > 0
  echo {"INDX_WRITE_STATE: saved to " ^ var.f ^ "  (scale " ^ global.INDX_LC_scale ^ " g/count, state " ^ global.INDX_State ^ ")"}
