; INDX persisted state - generated by INDX_WRITE_STATE, do not edit by hand.
; Run by INDX_variables.g to restore saved values and apply them to the probe.
; unloaded baseline when calibrated: -9828.438 counts
set global.INDX_LC_scale = 0.1752201
set global.INDX_LC_calibrated = true
set global.INDX_State = 99
set global.INDX_DEBUG = 1
M558 K0 V0.1752201
